language: python
python:
  - "3.6"
# command to install dependencies
install: 
- pip install -r requirements.txt
- sudo pip install nose
- sudo pip install coveralls
# command to run tests
script: pytest
