sudo: required
dist: trusty
language: python
sudo: required
python:
  - "3.4"
before_install:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip install coveralls
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
install:
  - npm install
  - sudo pip3 install -r requirements.txt
script: nosetests --with-coverage --cover-package=app
after_success:
  - coveralls

