language: python
sudo: required
python:
  - "3.5"
  - "3.6"
install:
  - "sudo apt-get install python3-pip"
  - "sudo pip install -r requirements.txt"
  - "sudo pip install coverage"
  - "sudo pip install coveralls"
script: nosetests --with-coverage --cover-package=app

after_success:
  - coveralls
